[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "HuHdLxGcUofNeDwtVkrk15XCNobg1KoaS51qGpZQvfdR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "../Turbin3_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
